=== sushilthapaIT/Music-Store-Website/catalog_19031753.dtd
<!ELEMENT SongStore (Shop,header,Intro,quote,Songs)>

<!ELEMENT Shop (shopLocation,shopNumber,shopWebsite)>
<!ATTLIST Shop shopID CDATA #REQUIRED>

<!ELEMENT shopLocation (#PCDATA)>
<!ELEMENT shopNumber (#PCDATA)>
<!ELEMENT shopWebsite (#PCDATA)>

<!ELEMENT header (logo?,shopName)>
<!ELEMENT logo (#PCDATA)>
<!ELEMENT shopName (#PCDATA)>

<!ELEMENT Intro (#PCDATA)>

<!ELEMENT quote (q1,q2,q3)>
<!ELEMENT q1 (#PCDATA)>
<!ELEMENT q2 (#PCDATA)>
<!ELEMENT q3 (#PCDATA)>

<!ELEMENT Songs (song+)>
<!ELEMENT song (songName?, musicName, songDescription, songINFORMATION)>

<!ELEMENT songName (#PCDATA)>
<!ATTLIST songName songID CDATA #REQUIRED>

<!ELEMENT musicName (#PCDATA)>

<!ELEMENT songDescription (h1,p)>
<!ELEMENT h1 (#PCDATA)>
<!ELEMENT p (#PCDATA)>

<!ELEMENT songINFORMATION (Information, artist, genre, alblum, director?, producer, writer, composer?, studio?, recordDate?, recordedBy?, releaseDate?, review, label?, stock, nomination?, price)>
<!ELEMENT Information (#PCDATA)>

<!ELEMENT artist (#PCDATA)>
<!ATTLIST artist artistID CDATA #REQUIRED>

<!ELEMENT genre (#PCDATA)>

<!ELEMENT alblum (#PCDATA)>
<!ATTLIST alblum alblumID CDATA #REQUIRED>

<!ELEMENT director (#PCDATA)>
<!ELEMENT producer (#PCDATA)>

<!ELEMENT writer (#PCDATA)>
<!ATTLIST writer writerID CDATA #REQUIRED>

<!ELEMENT composer (#PCDATA)>
<!ELEMENT studio (#PCDATA)>
<!ELEMENT recordDate (#PCDATA)>
<!ELEMENT recordedBy (#PCDATA)>
<!ELEMENT releaseDate (#PCDATA)>
<!ELEMENT review (#PCDATA)>
<!ELEMENT label (#PCDATA)>

<!ELEMENT stock (#PCDATA)>
<!ATTLIST stock stockID CDATA #REQUIRED>

<!ELEMENT nomination (#PCDATA)>

<!ELEMENT price (#PCDATA)>
<!ATTLIST price priceID CDATA #REQUIRED>

=== sushilthapaIT/Music-Store-Website/catalog_19031753.xml
<?xml version="1.0" encoding="UTF-8"?>
 <?xml-stylesheet types="text/css" href="catalog_19031753.css"?> 
 <!DOCTYPE SongStore SYSTEM "catalog_19031753.dtd"> 
<SongStore xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
				xsi:noNamespaceSchemaLocation="catalog_19031753.xsd">

	<Shop shopID="SH11-10">
		<shopLocation>Address: Durbarmaarg,Nepal</shopLocation>
		<shopNumber>Phone Number: 012377592</shopNumber>
		<shopWebsite>Website: www.dynamitemusic.com.np</shopWebsite>
	</Shop>
	<header>
		<logo></logo>
		<shopName>DYNAMiTE Music Store</shopName>
	</header>
	<Intro>Music For All</Intro>
	<quote>
	<q1>1990-2020</q1>
	<q2>Music Collections</q2>
	<q3>Available with Us Follow US</q3>
	</quote>
	<Songs>
		<song>	
			<songName songID="S1" ></songName>
			<musicName>Beautiful</musicName>
			<songDescription>
					<h1>Description</h1>
					<p>
					On this melancholy song Eminem raps about his struggles with drug addiction. In August 2005
					Eminem entered drug rehabilitation in order to treat a dependency on sleep medication. He subsequently
					took a break during which he battled his addiction whilst industry insiders speculated that Shady had
					ended his rapping career. Eminem is now sober and he told Vibe magazine that this song is the only one
					he kept from the recordings he made during that dark period in his life. He explained: "One of the only
					reasons that I put that track on there is that I feel like it's the best song out of that batch that I 
					did when I wasn't sober. At the time I felt like, 'This is it for me.' I wrote the first verse and a 
					half in rehab, and when I came out, I finished it. It was the only song that marks that period without 
					bringing me back to that place. Every other track not only didn't fit with the album, but when I listened
					to it, it would bring up bad memories. This was the 5th song of that title to chart in the Hot 100."
					</p>
			</songDescription>
			<songINFORMATION>
				<Information>Information</Information>
				<artist artistID="01" >Artist: Eminem</artist>
				<genre>Genres: Hip hop, Rap rock, Hip-Hop/Rap</genre>
				<alblum alblumID="A1" >Alblum: Relapse</alblum>
				<director>Director: Mike Strange</director>
				<producer>Producers: Eminem, Jeff Bass</producer>
				<writer writerID="00W1" >Songwriters: Marshall Mathers, Luis Resto, Jeffrey Bass, Don Black, Andy Hill</writer>
				<composer>Composer: Marshall Mathers, Luis Resto</composer>
				<studio>Recorded At: Aftermath Entertainment</studio>
				<recordDate>Recorded: 2007</recordDate>
				<recordedBy>Recorderd by: Mike Strange at 54 Sound in Ferndale, Michigan</recordedBy>
				<releaseDate>Released Year: 2009</releaseDate>
				<review>Review: 4star by Billboard</review>
				<stock stockID="S01" >Stock: Available</stock>
				<price priceID="PS1" >Price: 10$</price>
			</songINFORMATION>
		</song>
		
		
		
		
		
		
		<song>
			<songName songID="S2" ></songName>
			<musicName>"Godzilla"</musicName>
			<songDescription>
					<h1>Description: </h1>
					<p>
					"Godzilla" is a success in the United States and Europe. It debuted at number one in
					Finland and on both the UK Singles Chart and the Irish Singles Chart, becoming Eminem's
					tenth and ninth number-one single in the UK and Ireland, respectively, as well as the first
					for Juice Wrld posthumously and in total in both countries. It also went to number two in Flanders,
					the Czech Republic, Hungary, New Zealand, and Slovakia. It went to number three in Eminem's homeland,
					the United States, and went top ten in 20 regions. Outside Europe, it saw moderate success in Lebanon
					and Singapore, peaking inside the top 20 in those regions. As of November 3, the song has sold more than
					3 million units in the US and became eligible for 3 times platinum.
					</p>
			</songDescription>
			<songINFORMATION>
				<Information>Information</Information>
				<artist artistID="02" >Artist: Eminem ft. Juice WRLD</artist>
				<genre>Genres:  Alternative Hip-Hop/Rap</genre>
				<alblum alblumID="A2" >Alblum: Music to Be Murdered By</alblum>
				<director>Director: Taylor Randall</director>
				<producer>Producers: Eminem, D.A. Doman</producer>
				<writer writerID="00W2" >Songwriters: Marshall Mathers, Jarad Higgins, David Doman, Luis Resto, Alejandro Villasana</writer>
				<composer>Composer: Marshall Mathers, Luis Resto</composer>
				<studio>Recorded At: Shady Records</studio>
				<recordDate>Recorded: 2019</recordDate>
				<recordedBy>Recorderd by: Mike Strange at 54 Sound in Ferndale, Michigan</recordedBy>
				<releaseDate>Released Year: Janaury 28, 2020</releaseDate>
				<review>Review: 4star by Billboard</review>
				<stock stockID="S02" >Stock: Available</stock>
				<price priceID="PS2" >Price: 9$</price>
			</songINFORMATION>
		</song>
		
		
		
		
		
		
		<song>
			<songName songID="S3" ></songName>
			<musicName>"Junkeri/Fireflies"</musicName>
			<songDescription>
					<h1>Description: </h1>
					<p>
					Maya (English:Love) is the second studio album by Nepali singer and songwriter Bipul Chettri. 
					It was released on September 2, 2016 by OKListen Media and Bipul Chettri. The album is about
					his love for the Nepalese countryside hills that Chettri call's his home and the album is follow-up
					to Sketches of Darjeeling."
					</p>
			</songDescription>
			<songINFORMATION>
				<Information>Information</Information>
				<artist artistID="03" >Artist: Bipil Chettri</artist>
				<genre>Genres: Nepali Folk</genre>
				<alblum alblumID="A3" >Alblum: Maya</alblum>
				<director>Director: Bipul Chettr</director>
				<producer>Producers: Sonam Tashi</producer>
				<writer writerID="00W3" >Songwriters: Bipul Chettri</writer>
				<composer>Composer: Bipul Chettr</composer>
				<studio>Recorded At: Anindo Bose at ‘Plug ‘N’ Play’ Studios, India</studio>
				<recordDate>Recorded: September 2, 2016</recordDate>
				<recordedBy>Recorderd by: Binaya Man Amatya, Kathmandu, Nepal</recordedBy>
				<releaseDate>Released Year: 2009</releaseDate>
				<review>Review: 5star by MUSIC NEPAL</review>
				<stock stockID="S03" >Stock: Available</stock>
				<price priceID="PS3" >Price: 5$</price>
			</songINFORMATION>
		</song>
		
		
		
		
		
		
		<song>
			<songName songID="S4" ></songName>
			<musicName>"Life's A Mess"</musicName>
			<songDescription>
					<h1>Description</h1>
					<p>
					"Life's a Mess" is a song by American singers Juice Wrld and Halsey. It was released on July 6, 2020
					through Grade A Productions under exclusive license to Interscope Records as the third single for Juice
					Wrld's posthumous third studio album, Legends Never Die, and was later included on Halsey's Collabs EP
					that dropped 3 weeks after. It was released the same day that Juice Wrld's estate announced the album
					and the release date of it. This marks the second collaboration between the two artists, following the
					remix of Halsey's chart-topping single "Without Me".
					</p>
			</songDescription>
			<songINFORMATION>
				<Information>Information</Information>
				<artist artistID="04" >Artist: Juice WRLD, Halsey</artist>
				<genre>Genres: 	Emo rap-pop</genre>
				<alblum alblumID="A4" >Alblum: Legends Never Die</alblum>
				<director>Director: Luis Resto</director>
				<producer>Producers:  Rex Kudo; Heavy Mellow; Rick Rubin</producer>
				<writer writerID="00W4" >Songwriters: Jarad Higgins, Ashley Frangipane, Ryan Vojesak, Masamune Kudo</writer>
				<composer>Composer: Marshall Mathers, Luis Resto</composer>
				<studio>Recorded At: Aftermath Entertainment</studio>
				<recordDate>Recorded: 2019</recordDate>
				<recordedBy>Recorderd by: Mike Strange at 54 Sound in Ferndale, Michigan</recordedBy>
				<releaseDate>Released Year: July 6, 2020</releaseDate>
				<review>Review: 4star by Billboard</review>
				<stock stockID="S04" >Stock: Available</stock>
				<price priceID="PS4" >Price: 7$</price>
			</songINFORMATION>
		</song>
		
		
		
		
		
		
		<song>
			<songName songID="S5" ></songName>
			<musicName>"Tightrope"</musicName>
			<songDescription>
					<h1>Description</h1>
					<p>
					Nobody Is Listening is the third solo studio album by English singer-songwriter Zayn. 
					"Tightrope" is an acoustic-based love song that talks about how love and life are a balancing act.
					The deeper Zayn plunges into the relationship, the further the fall will be if it all goes wrong.
					Sometimes the singer feels insecure about committing himself more, but when he feels his grip is going,
					his lover is still there, holding onto his arm.
					</p>
			</songDescription>
			<songINFORMATION>
				<Information>Information</Information>
				<artist artistID="05" >Artist: Zayn Malik</artist>
				<genre>Genres: 	Pop RB</genre>
				<alblum alblumID="A5" >Alblum: Nobody Is Listening</alblum>
				<director>Director: Mike Strange</director>
				<producer>Producers: Zayn Malik, Charlie Handsome,David Harris, Ernest Keith Smith, Henrique Andrade</producer>
				<writer writerID="00W5" >Songwriters: Zayn Malik</writer>
				<composer>Composer: Unicorn Waves, Zachary Seman</composer>
				<studio>Recorded At: Major Tom's (London)Germano, the Mastering Place (New York City)</studio>
				<recordDate>Recorded: 2021</recordDate>
				<recordedBy>Recorderd by: Major Tom's </recordedBy>
				<releaseDate>Released Year: 15 January 2021</releaseDate>
				<review>Review: 6 star by Billboard</review>
				<stock stockID="S05" >Stock: Available</stock>
				<price priceID="PS5" >Price: 12$</price>
			</songINFORMATION>
		</song>
		
		
		
		
		
		
		<song>
			<songName songID="S6" ></songName>
			<musicName>"Save Your Tears"</musicName>
			<songDescription>
					<h1>Description</h1>
					<p>
